# NumPy

## NumPy配列の生成

In [1]:
import numpy as np

x = np.array([1.0, 2.0, 3.0])
print x

[1. 2. 3.]


In [2]:
type(x)

numpy.ndarray

## NumPyの算術演算
下記の4則演算は要素数が違う場合はエラーとなる

In [3]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])

In [4]:
x + y

array([3., 6., 9.])

In [5]:
x - y

array([-1., -2., -3.])

In [6]:
x * y

array([ 2.,  8., 18.])

In [7]:
x / y

array([0.5, 0.5, 0.5])

In [8]:
x / 2.0

array([0.5, 1. , 1.5])

## NumPyのN次元配列

In [9]:
A = np.array([[1, 2], [3, 4]])

In [10]:
print A

[[1 2]
 [3 4]]


In [11]:
A.shape

(2, 2)

In [12]:
A.dtype

dtype('int64')

In [13]:
B = np.array([[3, 0], [0, 6]])

In [14]:
A + B

array([[ 4,  2],
       [ 3, 10]])

In [15]:
A * B

array([[ 3,  0],
       [ 0, 24]])

## ブロードキャスト
要素が拡大されて演算される

In [16]:
print A
A * 10

[[1 2]
 [3 4]]


array([[10, 20],
       [30, 40]])

In [17]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])

In [18]:
A * B

array([[10, 40],
       [30, 80]])

## 多次元配列の計算

In [19]:
A = np.array([1, 2, 3, 4])
print A

[1 2 3 4]


In [20]:
np.ndim(A) # 配列の次元数

1

In [21]:
A.shape

(4,)

In [22]:
A.shape[0]

4

In [23]:
B = np.array([[1, 2], [3, 4], [5, 6]])
print B

[[1 2]
 [3 4]
 [5 6]]


In [24]:
np.ndim(B)

2

In [25]:
B.shape

(3, 2)

### 内積

In [26]:
A = np.array([[1, 2], [3, 4]])
A.shape

(2, 2)

In [27]:
B = np.array([[5, 6], [7, 8]])
B.shape

(2, 2)

In [28]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

## 要素へのアクセス

In [29]:
X = np.array([[51, 55], [14, 19], [0, 4]])
print X

[[51 55]
 [14 19]
 [ 0  4]]


### インデックス操作

In [30]:
X[0]

array([51, 55])

In [31]:
X[0][1]

55

In [32]:
for row in X:
    print row

[51 55]
[14 19]
[0 4]


### 配列によるアクセス

In [33]:
X = X.flatten() # 1次元配列へ変換
print X

[51 55 14 19  0  4]


In [34]:
type(X)

numpy.ndarray

In [35]:
X[np.array([0, 4, 2])] # インデックスが0, 4, 2番目の要素を取得

array([51,  0, 14])

In [36]:
X > 15 # 不等号の演算結果が配列になる

array([ True,  True, False,  True, False, False])

In [37]:
X[X>15] # Trueの部分だけ抜き出される

array([51, 55, 19])

## 参考
- ゼロから作るDeep Learning ―Pythonで学ぶディープラーニングの理論と実装