# NumPy Arrayの基礎

## NumPy Arrayの付属情報
ここでは一次元、二次元、三次元の3つのランダムなarrayを宣言する。

NumPyのランダム値のジェネレータを使用する。ここではコードを実行するたびに同じランダムarrayを生成するためにシードを設定している。

In [1]:
import numpy as np
np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

それぞれのarrayは以下の付属情報を持つ。

- `ndim`: 次元数
- `shape`: 各次元の大きさ
- `size`: array全体の大きさ
- `dtype`:arrayのデータタイプ
- `itemsize`:それぞれのarrayの要素のサイズ（byte)
- `nbytes`:arrayのトータルサイズ（byte)

In [2]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)
print("x3 dtype: ", x3.dtype)
print("x3 itemsize: ", x3.itemsize, "bytes")
print("x3 nbytes: ", x3.nbytes, "bytes")

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60
x3 dtype:  int64
x3 itemsize:  8 bytes
x3 nbytes:  480 bytes


通常、`nbytes`は`itemsize`と`size`の積と等しくなる。

## Arrayへのアクセス：一つの要素へのアクセス
一次元のarrayへのアクセスはPythonの標準的なリストと同様である。

In [3]:
x1

array([5, 0, 3, 3, 7, 9])

In [4]:
x1[0]

5

In [5]:
x1[4]

7

In [6]:
x1[-1]

9

多次元の場合には、コンマで分けられたタプルのインデックスでアクセスすることが可能。

In [7]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [8]:
x2[0, 0]

3

In [9]:
x2[2, 0]

1

In [10]:
x2[2, -1]

7

値の修正も上記のインデックス表記を使用して行うことができる。

In [11]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

ただし、型は固定されているため、ことなる型の値を利用することはできない。

例えば、もし浮動小数点の値をinteger arrayに挿入しようとした場合には、小数点以下の値は切り捨てられる。

In [12]:
x1[0] = 3.14159
x1

array([3, 0, 3, 3, 7, 9])

## arrayのスライス
標準的なPythonのリストと同様に、スライスを利用することができる。

### 1次元のsubarray

In [13]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
x[:5]

array([0, 1, 2, 3, 4])

In [15]:
x[5:]

array([5, 6, 7, 8, 9])

In [16]:
x[4:7]

array([4, 5, 6])

In [17]:
x[::2]

array([0, 2, 4, 6, 8])

In [18]:
x[1::2]

array([1, 3, 5, 7, 9])

In [19]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [20]:
x[5::-2]

array([5, 3, 1])

### 多次元のsubarray

In [21]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [22]:
x2[:2, :3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [23]:
x2[:3, ::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [24]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

行や列を1列抜き出したいような場合には、次のようにして行うことができる。

In [25]:
x2[:, 0]

array([12,  7,  1])

In [26]:
x2[0, :]

array([12,  5,  2,  4])

In [27]:
x2[0]

array([12,  5,  2,  4])

## Subarrayのノーコピービュー
NumPyのスライスはarrayのデータのコピーではなく、ビューを返す。コピーを返すPythonのリストとはそこが違う。

このデフォルトの振る舞いは実際かなり便利。つまり大きなデータセットを利用する際に、データバッファのコピー無しに、これらのデータセットの一部に対してアクセス、および処理を行うことが出来る。

In [28]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [29]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [30]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [31]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## arrayのコピー
コピーが必要な際は`copy()`メソッドを利用することができる。

In [32]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [33]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [34]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## arrayのリシェープ
`reshape`メソッドを利用すれば、arrayの形状を変更することが出来る。例えば、1次元のarrayを3次元のarrayに変更などが出来る。

In [35]:
grid = np.arange(1, 10).reshape(3, 3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


リシェープを行う際に、始めのarrayのサイズがリシェープ後のarrayのサイズと一致していなければならない。ここで、可能であれば`reshape`メソッドは始めのarrayのノーコピービューを使用するが、連続したメモリバッファでない場合には常にそうであるわけではない。

その他の一般的なリシェーピングのパターンは、1次元のarrayを2次元の行や列のマトリックスに変換することである。これは`reshape`メソッドによって実現できる他、スライスの操作のなかで`newaxis`キーワードを利用することで簡単に行うことが出来る。

In [36]:
x = np.array([1, 2, 3])

x.reshape((1,3))

array([[1, 2, 3]])

In [37]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [38]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

## Arrayの結合と分割
### Arrayの結合
arrayを結合する。結合後に返ってくるのはコピー。

In [39]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [40]:
z = [99, 99, 99]
np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [41]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [42]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [43]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [44]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [45]:
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

### Arrayの分割
分割するポイントとなるインデックスのリストを与えて分割を行う。

In [46]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [47]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [48]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [49]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
